export const FILTERS = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_COMPLETED: "SHOW_COMPLETED",
  SHOW_ACTIVE: "SHOW_ACTIVE",
};

export const FILTERS_TEXT = {
  [FILTERS.SHOW_ALL]: "All",
  [FILTERS.SHOW_COMPLETED]: "Completed",
  [FILTERS.SHOW_ACTIVE]: "Active",
};
